[build]
  command = "flutter build web"
  publish = "build/web"

[[plugins]]
package = "netlify-plugin-command-runner"
  [plugins.inputs]
    commands = [
      "git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter",
      "export PATH=\"$PATH:$HOME/flutter/bin\"",
      "flutter doctor" # Optional: to verify installation
    ]
