[build]
  command = "./build_script.sh"
  publish = "build/web" # This should be the directory where flutter build web outputs files

# If you have environment variables, define them here
[build.environment]
  SUPABASE_SERVICE_ROLE_KEY = "" # Replace with your actual environment variable name
