// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kDV-TuhIzbVaLPYi01o923RfScRUAzw',
    appId: '1:45209853406:web:ad0a6b91694718d144d14f',
    messagingSenderId: '45209853406',
    projectId: 'our-project-quickbot-e3c2f',
    authDomain: 'our-project-quickbot-e3c2f.firebaseapp.com',
    storageBucket: 'our-project-quickbot-e3c2f.firebasestorage.app',
    measurementId: 'G-ZZKNMGZFT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAjoJsWfUhXgBHgUBZT33fzUeCX6xbg4',
    appId: '1:45209853406:android:4e935539b535409744d14f',
    messagingSenderId: '45209853406',
    projectId: 'our-project-quickbot-e3c2f',
    storageBucket: 'our-project-quickbot-e3c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbOcvREQ-3nrmugarIHd-rYAZA6lRf6c',
    appId: '1:45209853406:ios:00f8c5eda58f652144d14f',
    messagingSenderId: '45209853406',
    projectId: 'our-project-quickbot-e3c2f',
    storageBucket: 'our-project-quickbot-e3c2f.firebasestorage.app',
    iosBundleId: 'com.example.qcuickbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbOcvREQ-3nrmugarIHd-rYAZA6lRf6c',
    appId: '1:45209853406:ios:00f8c5eda58f652144d14f',
    messagingSenderId: '45209853406',
    projectId: 'our-project-quickbot-e3c2f',
    storageBucket: 'our-project-quickbot-e3c2f.firebasestorage.app',
    iosBundleId: 'com.example.qcuickbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kDV-TuhIzbVaLPYi01o923RfScRUAzw',
    appId: '1:45209853406:web:7f07806fc5da702144d14f',
    messagingSenderId: '45209853406',
    projectId: 'our-project-quickbot-e3c2f',
    authDomain: 'our-project-quickbot-e3c2f.firebaseapp.com',
    storageBucket: 'our-project-quickbot-e3c2f.firebasestorage.app',
    measurementId: 'G-5MTEY1EQY5',
  );
}
